version: '3'
services:
  backend:
    build: ./backend-api
    container_name: backend-api
    environment:
      - MONGO_URI=mongodb+srv://username:password@cluster0.mongodb.net/dbname?retryWrites=true&w=majority
    ports:
      - "5002:5002" 
    volumes:
      - ./backend-api:/usr/src/app
    networks:
      - app-network

  frontend:
    build: ./frontend_schedetechiche
    container_name: frontend-app
    ports:
      - "3000:80"
    volumes:
      - ./frontend_schedetechiche:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
