# Utilizza Nixpacks come builder per il progetto
[build]
builder = "NIXPACKS"

# Configurazione per il Backend API (Node.js)
[deploy.backend]
startCommand = "cd backend-api && npm install && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Configurazione per il Frontend Gestore Prodotti (React)
[deploy.frontendgestoreprodotti]
startCommand = "cd frontendgestoreprodotti && npm install && npm run build && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Configurazione per il Frontend Catalogo (React)
[deploy.catalogo-frontend]
startCommand = "cd catalogo-frontend && npm install && npm run build && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Configurazione per il Frontend Catalogo Prodotti (React)
[deploy.frontend-catalogoprodotti]
startCommand = "cd frontend-catalogoprodotti && npm install && npm run build && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Configurazione per il Frontend Schede Tecniche (React)
[deploy.frontend_schedetechiche]
startCommand = "cd frontend_schedetechiche && npm install && npm run build && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
