# railway.toml

# Utilizza Nixpacks come builder per il progetto
[build]
builder = "NIXPACKS"

# Configurazione per il Backend API (Node.js)
[deploy]
startCommand = "cd backend-api && npm install && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
